name: Graphs CI
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  graphs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: upptime/graphs@v1.2.18
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
