name: Static Site CI
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  static-site:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: upptime/status-page@v1.17.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-pages-artifact@v3
        with:
          path: site
      - uses: actions/deploy-pages@v4
